version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: terra_stabilis_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  bot:
    build: ./bot
    container_name: terra_stabilis_bot
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - redis

  admin:
    build: ./admin
    container_name: terra_stabilis_admin
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis