# Generated by Django 4.2.9 on 2025-10-19 18:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BotUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.BigIntegerField(
                        help_text="ID пользователя в Telegram", unique=True
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="@username в Telegram",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, help_text="Имя", max_length=100, null=True
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, help_text="Фамилия", max_length=100, null=True
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Телефон", max_length=50, null=True
                    ),
                ),
                (
                    "has_shared_contact",
                    models.BooleanField(default=False, help_text="Поделился контактом"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Время первого взаимодействия",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Время последнего обновления"
                    ),
                ),
            ],
            options={
                "db_table": "bot_users",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BotUserEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        db_index=True, help_text="Тип события", max_length=100
                    ),
                ),
                (
                    "event_data",
                    models.JSONField(default=dict, help_text="Данные события в JSON"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="Время создания"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="bot_data.botuser",
                    ),
                ),
            ],
            options={
                "db_table": "bot_user_events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BotLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(help_text="Тип услуги", max_length=200),
                ),
                (
                    "calculated_price",
                    models.DecimalField(
                        decimal_places=2, help_text="Рассчитанная цена", max_digits=10
                    ),
                ),
                (
                    "is_converted",
                    models.BooleanField(default=False, help_text="Стал клиентом"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Заметки менеджера", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="Время создания"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leads",
                        to="bot_data.botuser",
                    ),
                ),
            ],
            options={
                "db_table": "bot_leads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BotCalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(help_text="Тип услуги", max_length=200),
                ),
                (
                    "parameters",
                    models.JSONField(default=dict, help_text="Параметры расчета"),
                ),
                ("result", models.TextField(help_text="Результат расчета")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Цена", max_digits=10
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="Время создания"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calculations",
                        to="bot_data.botuser",
                    ),
                ),
            ],
            options={
                "db_table": "bot_calculations",
                "ordering": ["-created_at"],
            },
        ),
    ]
