# Generated by Django 4.2.9 on 2025-10-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_data", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="botcalculation",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Расчет бота",
                "verbose_name_plural": "Расчеты бота",
            },
        ),
        migrations.AlterModelOptions(
            name="botlead",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Лид бота",
                "verbose_name_plural": "Лиды бота",
            },
        ),
        migrations.AlterModelOptions(
            name="botuser",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Пользователь бота",
                "verbose_name_plural": "Пользователи бота",
            },
        ),
        migrations.AlterModelOptions(
            name="botuserevent",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Событие бота",
                "verbose_name_plural": "События бота",
            },
        ),
        migrations.AlterField(
            model_name="botcalculation",
            name="service_type",
            field=models.CharField(
                db_index=True, help_text="Тип услуги", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="botlead",
            name="is_converted",
            field=models.BooleanField(
                db_index=True, default=False, help_text="Стал клиентом"
            ),
        ),
        migrations.AlterField(
            model_name="botlead",
            name="service_type",
            field=models.CharField(
                db_index=True, help_text="Тип услуги", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="botuser",
            name="phone",
            field=models.CharField(
                blank=True, db_index=True, help_text="Телефон", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="botuser",
            name="user_id",
            field=models.BigIntegerField(
                db_index=True, help_text="ID пользователя в Telegram", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="botuser",
            name="username",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="@username в Telegram",
                max_length=100,
                null=True,
            ),
        ),
    ]
