# Generated by Django 4.2.9 on 2025-10-14 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BotCalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.BigIntegerField(help_text="ID пользователя в Telegram"),
                ),
                (
                    "service_type",
                    models.CharField(help_text="Тип услуги", max_length=200),
                ),
                (
                    "parameters",
                    models.JSONField(default=dict, help_text="Параметры расчета"),
                ),
                ("result", models.TextField(help_text="Результат расчета")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Цена", max_digits=10
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="Время создания"
                    ),
                ),
            ],
            options={
                "db_table": "bot_calculations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BotLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Имя клиента", max_length=200)),
                ("phone", models.CharField(help_text="Телефон", max_length=50)),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Email", max_length=254, null=True
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, help_text="Компания", max_length=200, null=True
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        blank=True, help_text="Тип услуги", max_length=200, null=True
                    ),
                ),
                (
                    "calculated_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Рассчитанная цена",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="telegram", help_text="Источник", max_length=50
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="Время создания"
                    ),
                ),
            ],
            options={
                "db_table": "bot_leads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BotUserEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.BigIntegerField(help_text="ID пользователя в Telegram"),
                ),
                (
                    "event_type",
                    models.CharField(
                        db_index=True, help_text="Тип события", max_length=100
                    ),
                ),
                (
                    "event_data",
                    models.JSONField(default=dict, help_text="Данные события в JSON"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="Время создания"
                    ),
                ),
            ],
            options={
                "db_table": "bot_user_events",
                "ordering": ["-created_at"],
            },
        ),
    ]
